service: my-service
provider:
  name: aws
  runtime: nodejs14.x
  region: eu-north-1

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          path: hello
          method: get

resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: restapi-table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: string
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
